import type { Categoria } from "./types";

export const CATEGORIAS: Categoria[] = [
  {
    id: "lugares",
    nombre: "Lugares",
    emoji: "📍",
    palabras: {
      facil: [
        "Playa", "Aeropuerto", "Hospital", "Estadio", "Biblioteca", "Escuela",
        "Iglesia", "Banco", "Cine", "Restaurante", "Parque", "Supermercado",
        "Farmacia", "Cárcel", "Gimnasio", "Hotel", "Casino", "Zoológico",
        "Circo", "Bar", "Cafetería", "Panadería", "Peluquería", "Mercado",
        "Plaza", "Cementerio", "Museo", "Teatro", "Estación de tren", "Puerto",
        "Castillo", "Granja", "Bosque", "Montaña", "Desierto", "Selva",
        "Río", "Lago", "Isla", "Volcán", "Casa", "Oficina", "Jardín",
        "Heladería", "Kiosco", "Consultorio", "Sótano", "Balcón", "Terraza",
        "Shopping", "Estacionamiento", "Fuente", "Cascada", "Valle", "Cueva",
        "Colina", "Costa", "Bahía", "Muelle", "Sendero",
      ],
      medio: [
        "Observatorio", "Faro", "Acueducto", "Catacumbas", "Mansión", "Refugio",
        "Embajada", "Tribunal", "Laboratorio", "Astillero", "Mina", "Cantera",
        "Fábrica", "Almacén", "Estudio de televisión", "Estudio de grabación",
        "Pista de patinaje", "Boliche", "Karaoke", "Bolera", "Spa", "Sauna",
        "Crucero", "Submarino", "Estación espacial", "Cabaña", "Iglú", "Pirámide",
        "Coliseo", "Palacio", "Monasterio", "Abadía", "Sinagoga", "Mezquita",
        "Templo", "Pagoda", "Hipódromo", "Velódromo", "Ring de boxeo", "Vivero",
        "Fortaleza", "Muralla", "Central eléctrica", "Viñedo", "Olivar",
        "Plantación", "Represa", "Canal", "Puente colgante", "Túnel",
        "Autopista", "Aduana", "Consulado", "Geriátrico", "Invernadero",
        "Bodega", "Granero", "Establo", "Dique", "Planta potabilizadora",
      ],
      dificil: [
        "Reactor nuclear", "Búnker", "Refinería", "Catedral gótica", "Mausoleo",
        "Anfiteatro romano", "Acuario público", "Planetario", "Hangar",
        "Estación de bomberos", "Comisaría", "Morgue", "Sala de operaciones",
        "Sala de calderas", "Bodega de vino", "Destilería", "Cervecería artesanal",
        "Aserradero", "Curtiembre", "Salina", "Géiser", "Cráter", "Cenote",
        "Manglar", "Sabana", "Tundra", "Páramo", "Estepa", "Iceberg", "Atolón",
        "Fiordo", "Cañón", "Meseta", "Acantilado", "Arrecife de coral",
        "Cueva submarina", "Glaciar", "Oasis", "Pozo petrolero", "Salar",
        "Laguna", "Hayedo", "Alcazaba", "Zigurat", "Dolmen", "Necrópolis",
        "Escollera", "Albufera", "Brezal", "Taiga", "Delta", "Caldera volcánica",
        "Morrena", "Circo glaciar", "Archipiélago", "Estuario", "Marisma",
        "Criadero", "Polder", "Menhir",
      ],
    },
  },
  {
    id: "objetos",
    nombre: "Objetos",
    emoji: "🧰",
    palabras: {
      facil: [
        "Cepillo de dientes", "Pasta de dientes", "Peine", "Cepillo", "Toalla",
        "Jabón", "Champú", "Espejo", "Reloj", "Despertador", "Cama", "Almohada",
        "Sábana", "Manta", "Mesa", "Silla", "Sofá", "Sillón", "Lámpara", "Vela",
        "Linterna", "Paraguas", "Sombrero", "Anteojos", "Mochila", "Cartera",
        "Billetera", "Llaves", "Celular", "Computadora", "Televisión",
        "Control remoto", "Auriculares", "Cámara de fotos", "Cuchillo",
        "Tenedor", "Cuchara", "Plato", "Vaso", "Taza", "Puerta", "Ventana",
        "Cortina", "Alfombra", "Cuadro", "Libro", "Cuaderno", "Lápiz",
        "Lapicera", "Goma de borrar", "Regla", "Pelota", "Muñeca",
        "Osito de peluche", "Globo", "Bolsa", "Caja", "Llavero", "Cartuchera",
        "Maleta",
      ],
      medio: [
        "Tijera", "Pinza", "Martillo", "Destornillador", "Llave inglesa",
        "Cinta métrica", "Nivel", "Taladro", "Sierra", "Pala", "Rastrillo",
        "Manguera", "Regadera", "Maceta", "Escoba", "Aspiradora", "Plancha",
        "Tabla de planchar", "Lavarropas", "Secarropas", "Heladera", "Microondas",
        "Horno", "Tostadora", "Licuadora", "Batidora", "Cafetera",
        "Pava eléctrica", "Termo", "Bandeja", "Sartén", "Olla", "Colador",
        "Rallador", "Abrelatas", "Sacacorchos", "Cucharón", "Espátula", "Mortero",
        "Embudo", "Ventilador", "Aire acondicionado", "Calefactor", "Estufa",
        "Secador de pelo", "Planchita", "Máquina de coser", "Balanza",
        "Caja fuerte", "Extintor", "Impresora", "Router", "Parlante",
        "Proyector", "Caja de herramientas", "Encendedor", "Fósforos",
        "Basurero", "Lupa de mano", "Reloj de pared",
      ],
      dificil: [
        "Astrolabio", "Sextante", "Brújula", "Catalejo", "Microscopio",
        "Estetoscopio", "Termómetro", "Barómetro", "Higrómetro", "Anemómetro",
        "Pluviómetro", "Tensiómetro", "Lupa", "Caleidoscopio", "Diapasón",
        "Metrónomo", "Teodolito", "Plomada", "Compás", "Transportador",
        "Escuadra", "Cartabón", "Pantógrafo", "Yunque", "Fuelle", "Soplete",
        "Cincel", "Buril", "Gubia", "Lima", "Esmeril", "Garlopa",
        "Cepillo de carpintero", "Berbiquí", "Punzón", "Calibre", "Goniómetro",
        "Estilete", "Aerógrafo", "Tipómetro", "Torno", "Fresadora", "Alicates",
        "Mazo", "Escariador", "Escofina", "Formón", "Escalímetro", "Tamiz",
        "Criba", "Ábaco", "Regla de cálculo", "Telémetro", "Odómetro",
        "Refractómetro", "Densímetro", "Almádena", "Llave de tubo",
        "Alcoholímetro", "Trompo",
      ],
    },
  },
  {
    id: "profesiones",
    nombre: "Profesiones",
    emoji: "👔",
    palabras: {
      facil: [
        "Médico", "Profesor", "Bombero", "Policía", "Cocinero", "Panadero",
        "Carpintero", "Plomero", "Electricista", "Mecánico", "Cartero", "Taxista",
        "Camionero", "Piloto", "Azafata", "Veterinario", "Dentista", "Enfermero",
        "Peluquero", "Albañil", "Pintor", "Jardinero", "Granjero", "Pescador",
        "Cantante", "Actor", "Bailarín", "Músico", "Futbolista", "Boxeador",
        "Tenista", "Nadador", "Periodista", "Fotógrafo", "Escritor", "Dibujante",
        "Mago", "Payaso", "Astronauta", "Soldado", "Maestro", "Chofer", "Mozo",
        "Vendedor", "Cajero", "Limpiador", "Guardia", "Niñera", "Chef", "Cura",
        "Mensajero", "Repartidor", "Marinero", "Minero", "Secretario",
        "Presentador", "Modelo", "Barbero", "Ciclista", "Árbitro",
      ],
      medio: [
        "Cirujano", "Abogado", "Juez", "Arquitecto", "Ingeniero", "Programador",
        "Diseñador gráfico", "Contador", "Economista", "Psicólogo", "Psiquiatra",
        "Pediatra", "Cardiólogo", "Oculista", "Optometrista", "Quiropráctico",
        "Sastre", "Modista", "Joyero", "Relojero", "Zapatero", "Florista",
        "Sommelier", "Repostero", "Heladero", "Carnicero", "Pescadero", "Apicultor",
        "Buzo", "Salvavidas", "Guardabosque", "Domador", "Adiestrador", "Locutor",
        "Comentarista deportivo", "Director de cine", "Productor", "Guionista",
        "Coreógrafo", "Estilista", "Traductor", "Intérprete", "Docente",
        "Farmacéutico", "Químico", "Físico", "Matemático", "Astrónomo",
        "Investigador", "Auditor", "Ingeniero civil", "Ingeniero electrónico",
        "Ingeniero de software", "Mecánico naval", "Maquinista", "Desarrollador web",
        "Agente inmobiliario", "Administrador", "Publicista", "Analista",
      ],
      dificil: [
        "Forense", "Antropólogo", "Arqueólogo", "Paleontólogo", "Astrofísico",
        "Biólogo marino", "Geólogo", "Vulcanólogo", "Sismólogo", "Meteorólogo",
        "Climatólogo", "Etólogo", "Ornitólogo", "Entomólogo", "Botánico",
        "Taxidermista", "Calígrafo", "Lutier", "Restaurador de obras",
        "Curador de arte", "Anticuario", "Tasador", "Notario", "Escribano",
        "Diplomático", "Embajador", "Cónsul", "Traductor jurídico", "Catador",
        "Maestro chocolatero", "Maestro quesero", "Tonelero", "Herrero",
        "Forjador", "Vidriero", "Ebanista", "Talabartero", "Sereno", "Acuñador",
        "Perfumista", "Lexicógrafo", "Paleógrafo", "Archivero", "Cartógrafo",
        "Estenógrafo", "Pocero", "Techador", "Deshollinador", "Afilador",
        "Bioquímico", "Micólogo", "Helmintólogo", "Sinólogo", "Egiptólogo",
        "Grafólogo", "Sexólogo", "Ictiólogo", "Malacólogo", "Hematólogo",
        "Numismático",
      ],
    },
  },
  {
    id: "cine",
    nombre: "Películas y series",
    emoji: "🎬",
    palabras: {
      facil: [
        "Titanic", "Avatar", "Frozen", "Shrek", "Coco", "Toy Story", "Cars",
        "Buscando a Nemo", "El Rey León", "Aladdín", "Harry Potter",
        "El Señor de los Anillos", "Star Wars", "Indiana Jones", "Rocky",
        "Rápido y Furioso", "Misión Imposible", "Jurassic Park", "Tiburón",
        "E.T.", "Terminator", "Forrest Gump", "Matrix", "Karate Kid",
        "Volver al Futuro", "Hombres de Negro", "La Casa de Papel",
        "Stranger Things", "Breaking Bad", "Juego de Tronos", "The Office",
        "Friends", "Los Simpson", "Bob Esponja", "Pokémon", "Dragon Ball",
        "Peppa Pig", "Scooby-Doo", "Tom y Jerry", "El Chavo del 8",
        "Piratas del Caribe", "Mi pobre angelito", "Rey Arturo",
        "Los Vengadores", "La Sirenita", "La Bella y la Bestia",
        "Blancanieves", "La Cenicienta", "Mulán", "Moana", "Encanto",
        "Enredados", "Ratatouille", "Los Increíbles", "Monsters Inc", "WALL-E",
        "Intensamente", "Kung Fu Panda", "La Era de Hielo", "Madagascar",
      ],
      medio: [
        "El Padrino", "Pulp Fiction", "El Club de la Pelea", "Gladiador",
        "Corazón Valiente", "El Origen", "Interestelar", "El Caballero de la Noche",
        "Joker", "Parásitos", "El Sexto Sentido", "El Resplandor", "Psicosis",
        "Vértigo", "Casablanca", "Lo que el viento se llevó", "El Ciudadano Kane",
        "La Naranja Mecánica", "La Lista de Schindler",
        "Salvando al Soldado Ryan", "Apocalipsis Ahora", "Cadena Perpetua",
        "Doce Hombres en Pugna", "El Silencio de los Inocentes", "Halloween",
        "Pesadilla en Elm Street", "Viernes 13", "El Exorcista", "Alien",
        "Depredador", "Robocop", "Mad Max", "El Viaje de Chihiro",
        "La Princesa Mononoke", "La Vida es Bella", "Cinema Paradiso", "Amélie",
        "Whiplash", "La La Land", "Dune", "Toro Salvaje", "Taxi Driver",
        "Buenos Muchachos", "Caracortada", "El Pianista", "Memento",
        "Réquiem por un Sueño", "Perdidos en Tokio", "Gravity", "El Renacido",
        "Logan", "El Show de Truman", "Amores Perros", "Una Mente Brillante",
        "El Cisne Negro", "Magnolia", "Sin Lugar para los Débiles", "Los Otros",
        "El Orfanato", "Mystic River",
      ],
      dificil: [
        "Persona", "Stalker", "El Espejo", "Andrei Rublev", "Sátántangó",
        "Mulholland Drive", "Eraserhead", "La Dolce Vita", "8½",
        "El Año Pasado en Marienbad", "Hiroshima Mon Amour", "Cleo de 5 a 7",
        "Sin Aliento", "Los 400 Golpes", "La Ventana Indiscreta", "Roma",
        "Cría Cuervos", "El Espíritu de la Colmena", "Stroszek",
        "Aguirre la Cólera de Dios", "La Montaña Sagrada", "Suspiria",
        "Posesión", "La Pianista", "Funny Games", "El Verdugo",
        "Plácido", "Bienvenido Mr. Marshall", "La Estrategia del Caracol",
        "El Abrazo de la Serpiente", "La Historia Oficial",
        "Tiempo de Revancha", "Esperando la Carroza", "Pizza Birra Faso",
        "El Bonaerense", "El Secreto de sus Ojos", "Relatos Salvajes",
        "Anatomía de una Caída", "Tár", "La Sociedad de la Nieve", "Solaris",
        "Viridiana", "Un Perro Andaluz", "Los Santos Inocentes",
        "Amanece Que No Es Poco", "El Sur", "Los Olvidados",
        "La Piel que Habito", "Caché", "Amour", "Ida", "Melancolía",
        "Antes del Amanecer", "El Día de la Bestia", "La Caza", "Oldboy",
        "Dogville", "La Edad de Oro", "Macario", "Los Idiotas",
      ],
    },
  },
  {
    id: "animales",
    nombre: "Animales",
    emoji: "🐾",
    palabras: {
      facil: [
        "León", "Tigre", "Elefante", "Jirafa", "Cebra", "Hipopótamo", "Rinoceronte",
        "Mono", "Oso", "Lobo", "Zorro", "Conejo", "Ardilla", "Caballo", "Vaca",
        "Cerdo", "Oveja", "Cabra", "Gallina", "Perro", "Gato", "Ratón", "Ballena",
        "Tiburón", "Delfín", "Pulpo", "Cangrejo", "Pez", "Tortuga", "Cocodrilo",
        "Serpiente", "Águila", "Loro", "Pingüino", "Pato", "Búho", "Mariposa",
        "Abeja", "Hormiga", "Araña", "Gusano", "Mosca", "Mosquito", "Cucaracha",
        "Caracol", "Rana", "Sapo", "Lagartija", "Paloma", "Gorrión", "Cuervo",
        "Gaviota", "Canario", "Dinosaurio", "Hámster", "Cobayo", "Toro", "Burro",
        "Pony", "Saltamontes",
      ],
      medio: [
        "Camello", "Llama", "Alpaca", "Búfalo", "Antílope", "Gacela", "Ñu",
        "Hiena", "Leopardo", "Pantera", "Puma", "Lince", "Mapache", "Castor",
        "Nutria", "Foca", "Morsa", "Manatí", "Orca", "Manta raya",
        "Caballito de mar", "Estrella de mar", "Erizo de mar", "Medusa",
        "Calamar", "Langosta", "Camarón", "Cóndor", "Halcón", "Flamenco",
        "Pelícano", "Tucán", "Avestruz", "Emú", "Kiwi", "Ornitorrinco", "Koala",
        "Canguro", "Wombat", "Perezoso", "Hurón", "Erizo", "Topo", "Chinchilla",
        "Mofeta", "Garza", "Cisne", "Ibis", "Buitre", "Pavo real", "Faisán",
        "Urraca", "Lechuza", "Guacamayo", "Tarántula", "Mantis religiosa",
        "Libélula", "Ganso", "Alce", "Ciervo",
      ],
      dificil: [
        "Narval", "Beluga", "Cachalote", "Marsopa", "Vaquita marina", "Axolote",
        "Salamandra", "Tritón", "Iguana", "Camaleón", "Dragón de Komodo", "Gavial",
        "Tapir", "Okapi", "Quokka", "Numbat", "Pangolín", "Armadillo",
        "Oso hormiguero", "Suricata", "Glotón", "Zarigüeya", "Murciélago",
        "Tarsero", "Aye-aye", "Lemur", "Surubí", "Pirarucú", "Anguila eléctrica",
        "Quetzal", "Casuario", "Albatros", "Frailecillo", "Cormorán",
        "Garza real", "Martín pescador", "Colibrí", "Polilla luna", "Escorpión",
        "Capibara", "Yacaré", "Caimán", "Mandril", "Gibón", "Siamang",
        "Babirusa", "Mono aullador", "Yaguareté", "Gepardo", "Serval", "Caracal",
        "Ocelote", "Margay", "Dingo", "Bongó", "Órix", "Markhor", "Kudú",
        "Tamandúa", "Pecarí",
      ],
    },
  },
  {
    id: "famosos",
    nombre: "Famosos",
    emoji: "🌟",
    palabras: {
      facil: [
        "Shakira", "Bad Bunny", "Taylor Swift", "Justin Bieber", "Rihanna",
        "Beyoncé", "Lady Gaga", "Madonna", "Eminem", "Drake", "Ariana Grande",
        "Selena Gomez", "Dua Lipa", "Billie Eilish", "Ed Sheeran", "Bruno Mars",
        "The Weeknd", "Post Malone", "Karol G", "J Balvin", "Tom Cruise",
        "Brad Pitt", "Leonardo DiCaprio", "Will Smith", "Robert Downey Jr.",
        "Scarlett Johansson", "Angelina Jolie", "Jennifer Aniston", "Penélope Cruz",
        "Antonio Banderas", "Keanu Reeves", "Chris Hemsworth", "Chris Evans",
        "Dwayne Johnson", "Ryan Reynolds", "Jennifer Lopez", "Nicki Minaj",
        "Kim Kardashian", "Kylie Jenner", "Elon Musk", "Michael Jackson",
        "Elvis Presley", "Freddie Mercury", "John Lennon", "Paul McCartney",
        "Mick Jagger", "Bob Marley", "David Bowie", "Whitney Houston",
        "Mariah Carey", "Cher", "Britney Spears", "Christina Aguilera",
        "Oprah Winfrey", "Ellen DeGeneres", "Barack Obama", "Donald Trump",
        "Bill Gates", "Mark Zuckerberg", "Jennifer Garner",
      ],
      medio: [
        "Harry Styles", "Zayn Malik", "Timothée Chalamet", "Zendaya",
        "Florence Pugh", "Margot Robbie", "Ryan Gosling", "Emma Stone",
        "Emma Watson", "Tom Holland", "Pedro Pascal", "Oscar Isaac",
        "Natalie Portman", "Jennifer Lawrence", "Anne Hathaway", "Meryl Streep",
        "Denzel Washington", "Morgan Freeman", "Al Pacino", "Robert De Niro",
        "Adele", "Miley Cyrus", "Katy Perry", "Sam Smith", "Doja Cat", "SZA",
        "Olivia Rodrigo", "Camila Cabello", "Shawn Mendes", "Rauw Alejandro",
        "Rosalía", "Anuel AA", "Becky G", "Ozuna", "Daddy Yankee", "Maluma",
        "Enrique Iglesias", "Ricky Martin", "Luis Miguel", "Luis Fonsi",
        "Jason Momoa", "Idris Elba", "Samuel L. Jackson", "Hugh Jackman",
        "Jake Gyllenhaal", "Joaquin Phoenix", "Matthew McConaughey",
        "Cate Blanchett", "Nicole Kidman", "Sandra Bullock", "Julia Roberts",
        "Charlize Theron", "Reese Witherspoon", "Halle Berry", "Gal Gadot",
        "Viola Davis", "Mark Ruffalo", "Jeff Bezos", "Steve Jobs",
        "Gwyneth Paltrow",
      ],
      dificil: [
        "Florence Welch", "Lana del Rey", "Halsey", "Lorde", "Sabrina Carpenter",
        "Tate McRae", "PinkPantheress", "Ice Spice", "Kali Uchis", "Charli XCX",
        "FKA twigs", "Janelle Monáe", "Donald Glover", "Travis Scott", "21 Savage",
        "Megan Thee Stallion", "Lizzo", "Cardi B", "Tyler the Creator",
        "Frank Ocean", "Kendrick Lamar", "Phoebe Bridgers", "Mitski", "Clairo",
        "Bon Iver", "The 1975", "Tame Impala", "Arctic Monkeys", "Regé-Jean Page",
        "Jodie Comer", "Saoirse Ronan", "Michaela Coel", "Lupita Nyong'o",
        "Adam Driver", "Tilda Swinton", "Daniel Kaluuya", "John Boyega",
        "Barry Keoghan", "Paul Mescal", "Andrew Scott", "Aubrey Plaza",
        "Anya Taylor-Joy", "Jenna Ortega", "Austin Butler", "Elle Fanning",
        "Dakota Johnson", "Cillian Murphy", "Benedict Cumberbatch", "Rami Malek",
        "Christoph Waltz", "Javier Bardem", "Pedro Almodóvar", "Greta Gerwig",
        "Phoebe Waller-Bridge", "Ke Huy Quan", "Michelle Yeoh",
        "Sydney Sweeney", "Jacob Elordi", "Sebastian Stan", "Hunter Schafer",
      ],
    },
  },
  {
    id: "comidas",
    nombre: "Comidas y bebidas",
    emoji: "🍕",
    palabras: {
      facil: [
        "Pizza", "Hamburguesa", "Pancho", "Empanada", "Sándwich", "Milanesa",
        "Pollo asado", "Bife", "Pasta", "Espagueti", "Lasaña", "Sopa", "Ensalada",
        "Arroz", "Tortilla", "Tacos", "Burrito", "Sushi", "Helado", "Torta",
        "Galleta", "Chocolate", "Caramelo", "Manzana", "Banana", "Naranja",
        "Frutilla", "Sandía", "Pan", "Queso", "Café", "Té", "Leche",
        "Jugo de naranja", "Agua mineral", "Cerveza", "Vino", "Limonada",
        "Chocolate caliente", "Gaseosa", "Huevo", "Salchicha", "Tocino", "Jamón",
        "Papas fritas", "Puré de papas", "Yogur", "Cereal", "Mermelada",
        "Manteca", "Azúcar", "Sal", "Salsa golf", "Mayonesa", "Mostaza",
        "Dulce de membrillo", "Flan", "Gelatina", "Budín", "Medialuna",
      ],
      medio: [
        "Paella", "Risotto", "Ramen", "Pad thai", "Curry", "Falafel", "Hummus",
        "Kebab", "Ceviche", "Asado", "Choripán", "Guacamole", "Tamales", "Mole",
        "Arepa", "Pupusa", "Locro", "Humita", "Provoleta", "Croqueta",
        "Tarta de manzana", "Tiramisú", "Torta de queso", "Crème brûlée",
        "Fondue", "Raclette", "Croissant", "Bagel", "Pretzel", "Dulce de leche",
        "Alfajor", "Mate", "Café con leche", "Capuchino", "Espresso", "Daiquiri",
        "Mojito", "Margarita", "Sangría", "Champán", "Quiche", "Suflé", "Waffle",
        "Panqueques", "Chimichurri", "Ñoquis", "Ravioles", "Canelones",
        "Pastel de papas", "Puchero", "Mondongo", "Feijoada", "Tortilla española",
        "Fabada", "Migas", "Escabeche", "Carbonada", "Matambre", "Sorrentinos",
        "Milanesa napolitana",
      ],
      dificil: [
        "Bullabesa", "Coq au vin", "Beef wellington", "Carbonara", "Osobuco",
        "Carpaccio", "Bruschetta", "Caprese", "Gazpacho", "Pulpo a la gallega",
        "Bacalao a la vizcaína", "Cochinillo", "Pato pekinés", "Dim sum", "Wonton",
        "Tom yum", "Pho", "Bibimbap", "Kimchi", "Tempura", "Sashimi", "Onigiri",
        "Mochi", "Baklava", "Tahini", "Tabule", "Cuscús", "Musaca", "Pierogi",
        "Goulash", "Strudel", "Macaron", "Profiterol", "Praliné",
        "Trufa de chocolate", "Absenta", "Hidromiel", "Sake", "Pisco sour",
        "Caipirinha", "Cochifrito", "Manitas de cerdo", "Callos a la madrileña",
        "Rabo de toro", "Ajoblanco", "Zarzuela de mariscos", "Txangurro",
        "Kokotxas", "Pintxos", "Pa amb tomàquet", "Borscht", "Pelmeni",
        "Schnitzel", "Sauerbraten", "Takoyaki", "Okonomiyaki", "Gyoza",
        "Chateaubriand", "Vitello tonnato", "Risi e bisi",
      ],
    },
  },
  {
    id: "deportes",
    nombre: "Deportes",
    emoji: "⚽",
    palabras: {
      facil: [
        "Messi", "Cristiano Ronaldo", "Neymar", "Maradona", "Pelé", "Ronaldinho",
        "Zidane", "Iniesta", "Xavi", "Ronaldo Nazário", "Luis Suárez",
        "Sergio Ramos", "Mbappé", "Haaland", "Di María", "Michael Jordan",
        "LeBron James", "Kobe Bryant", "Shaquille O'Neal", "Stephen Curry",
        "Magic Johnson", "Kevin Durant", "Kyrie Irving", "Giannis Antetokounmpo",
        "Kareem Abdul-Jabbar", "La Mano de Dios", "El Gol del Siglo", "The Shot",
        "The Flu Game", "El Último Baile", "El Maracanazo",
        "El Milagro de Estambul", "La Remontada del Barça",
        "Final del Mundial 2022", "Dream Team", "Chilena de Bale", "Hat-trick",
        "Triplete", "Gol olímpico", "Balón de Oro", "Gabriel Batistuta",
        "Rafael Nadal", "Roger Federer", "Novak Djokovic", "Usain Bolt",
        "Michael Phelps", "Serena Williams", "Tiger Woods", "Muhammad Ali",
        "Mike Tyson", "Floyd Mayweather", "Canelo Álvarez", "Valentino Rossi",
        "Lewis Hamilton", "Fernando Alonso", "Juan Manuel Fangio", "Dibu Martínez",
        "Boca Juniors", "River Plate", "Clavada",
      ],
      medio: [
        "Jude Bellingham", "Kevin De Bruyne", "Harry Kane", "Mohamed Salah",
        "Sadio Mané", "Antoine Griezmann", "Paul Pogba", "Toni Kroos",
        "Luka Modrić", "Robert Lewandowski", "Pedri", "Gavi", "Vinicius Jr",
        "Rodrygo", "Lautaro Martínez", "Paulo Dybala", "Julián Álvarez",
        "Emiliano Martínez", "Thibaut Courtois", "Virgil van Dijk",
        "Son Heung-min", "Luka Dončić", "Nikola Jokić", "Joel Embiid",
        "Jayson Tatum", "Damian Lillard", "James Harden", "Russell Westbrook",
        "Klay Thompson", "Draymond Green", "Anthony Davis", "Kawhi Leonard",
        "Paul George", "Jimmy Butler", "El Cabezazo de Zidane a Materazzi",
        "La Atajada del Dibu", "El 6-1 del Barça al PSG",
        "El 7-1 de Alemania a Brasil", "Gol de Maxi Rodríguez",
        "La Chilena de Ibrahimović", "Carlos Alcaraz", "Stefanos Tsitsipas",
        "Iga Świątek", "Naomi Osaka", "Simone Biles", "Max Verstappen",
        "Charles Leclerc", "Lando Norris", "Sebastian Vettel", "Ricky Rubio",
        "Marc Gasol", "Conor McGregor", "Khabib Nurmagomedov", "Anthony Joshua",
        "Tyson Fury", "Argentina Campeón 2022", "Francia Campeón 2018",
        "Alemania Mundial 2014", "La Volcada de Ginóbili", "Gol de Palermo a Perú",
      ],
      dificil: [
        "Juan Román Riquelme", "Manu Ginóbili", "Luis Scola", "Pau Gasol",
        "Dirk Nowitzki", "Tony Parker", "Bill Russell", "Wilt Chamberlain",
        "Oscar Robertson", "John Stockton", "Karl Malone", "Steve Nash",
        "Patrick Ewing", "Charles Barkley", "David Robinson", "Hakeem Olajuwon",
        "Allen Iverson", "Reggie Miller", "Scottie Pippen", "Dennis Rodman",
        "Paolo Maldini", "Franz Beckenbauer", "Johan Cruyff", "Ferenc Puskás",
        "Alfredo Di Stéfano", "George Best", "Michel Platini", "Andrea Pirlo",
        "Lothar Matthäus", "Francesco Totti", "Ricardo Bochini", "Omar Sívori",
        "Zico", "Romário", "Rivaldo", "Kaká", "La Cucharita de Panenka",
        "La Chilena de Rooney", "El Dedo a Van der Sar", "El Tango del '86",
        "Roberto Baggio", "Gianluigi Buffon", "Iker Casillas", "Fabio Cannavaro",
        "Gerd Müller", "Franco Baresi", "Carles Puyol", "David Beckham",
        "Raúl González", "Hugo Sánchez", "Teófilo Cubillas", "Elías Figueroa",
        "Marcelo Bielsa", "César Luis Menotti", "Carlos Bilardo",
        "El Milagro de Berna", "La Naranja Mecánica de Holanda", "El Tiki-Taka",
        "La Garra Charrúa", "La Nuestra",
      ],
    },
  },
  {
    id: "superheroes",
    nombre: "Superhéroes y villanos",
    emoji: "🦸",
    palabras: {
      facil: [
        "Spider-Man", "Iron Man", "Batman", "Superman", "Mujer Maravilla",
        "Hulk", "Thor", "Capitán América", "Viuda Negra", "Ojo de Halcón",
        "Flash", "Aquaman", "Robin", "Guasón", "Thanos", "Linterna Verde",
        "Wolverine", "Deadpool", "Magneto", "Venom", "Duende Verde",
        "Lex Luthor", "Harley Quinn", "Gatúbela", "Doctor Octopus", "Loki",
        "Groot", "Rocket Raccoon", "Star-Lord", "Doctor Strange", "Ant-Man",
        "Pantera Negra", "Profesor X", "Cíclope", "Tormenta", "Capitana Marvel",
        "Nick Fury", "Visión", "Jean Grey", "Bruja Escarlata", "Gamora",
        "Nébula", "Drax", "Mantis", "Shazam", "Flecha Verde", "Starfire",
        "Raven", "Pícara", "Bestia", "Ciborg", "Nocturno", "Canario Negro",
        "Cazadora", "Mujer Araña", "Saitama", "All Might", "Mr. Increíble",
        "Astro Boy", "Iron Giant",
      ],
      medio: [
        "Soldado de Invierno", "Halcón", "Shuri", "Hela", "Ultron", "Cráneo Rojo",
        "Kingpin", "Kraven el Cazador", "Electro", "Lagarto", "Sandman",
        "Buitre", "Mysterio", "Mandarín", "Killmonger", "Darkseid", "Brainiac",
        "Doomsday", "Hiedra Venenosa", "Ra's al Ghul", "Bane", "Espantapájaros",
        "Acertijo", "Deathstroke", "Silver Surfer", "Galactus", "Doctor Doom",
        "Hellboy", "Spawn", "Avispa", "Supergirl", "Batgirl", "Mercurio",
        "Antorcha Humana", "La Cosa", "Mr. Fantástico", "Mujer Invisible",
        "Daredevil", "Punisher", "Blade", "Dr. Manhattan", "Ozymandias",
        "Rorschach", "Búho Nocturno", "Comediante", "V de Vendetta",
        "Constantine", "Hombre Plástico", "Animal Man", "Kid Flash",
        "Blue Beetle", "Firestorm", "Capitán Átomo", "Rayo Negro", "Medusa",
        "Spider-Gwen", "Miles Morales", "América Chávez", "Ms. Marvel",
        "Kate Bishop",
      ],
      dificil: [
        "Caballero Luna", "Sentry", "Bullseye", "Shang-Chi", "Namor",
        "Apocalipsis", "Dientes de Sable", "Mister Siniestro", "Emma Frost",
        "Psylocke", "Gambito", "Coloso", "Kitty Pryde", "Iceman",
        "Arcángel", "Bishop", "Cable", "Domino", "Jubilee", "Carnage",
        "Hobgoblin", "Hombre Topo", "Kang el Conquistador", "Barón Zemo",
        "M.O.D.O.K.", "Iron Fist", "Luke Cage", "Jessica Jones", "She-Hulk",
        "Morbius", "Sinestro", "Cheetah", "Black Adam", "Capitán Frío",
        "Gorilla Grodd", "Flash Reverso", "Black Manta", "Zatanna", "Omni-Man",
        "Invincible", "Korvac", "Nova", "Quasar", "Hombre Molécula", "Spectrum",
        "Polaris", "Havok", "Longshot", "Dazzler", "Banshee", "Cannonball",
        "Siryn", "Multiple Man", "Cypher", "Warlock", "Karma", "Rictor",
        "Magik", "Mirage", "Gladiador",
      ],
    },
  },
  {
    id: "culturapop",
    nombre: "Cultura pop",
    emoji: "🎤",
    palabras: {
      facil: [
        "Harlem Shake", "Gangnam Style", "Ice Bucket Challenge", "TikTok",
        "Instagram", "Twitter", "Facebook", "YouTube", "Snapchat", "WhatsApp",
        "Netflix", "Spotify", "Squid Game", "Merlina", "K-pop", "BTS",
        "Blackpink", "Reggaeton", "Trap", "Baby Shark", "Despacito", "Macarena",
        "Barbie", "Oppenheimer", "Emoji", "Meme", "Met Gala", "Oscar",
        "Grammys", "Emmy", "Fortnite Dance", "Just Dance", "Boomer", "Zoomer",
        "Millennial", "Selfie", "Hashtag", "Cara de pato", "Viral", "Trending",
        "Twitch", "Discord", "Reddit", "Pinterest", "LinkedIn", "Telegram",
        "Influencer", "Youtuber", "Podcast", "Streamer", "Gamer", "Anime",
        "Manga", "Cosplay", "Otaku", "Cancelado", "Like", "Story", "Filtro",
        "Emoji de corazón",
      ],
      medio: [
        "Nyan Cat", "Doge", "Pepe the Frog", "Grumpy Cat", "Rickroll", "Bitcoin",
        "NFT", "ChatGPT", "Metaverso", "Zoom", "Reels", "Stories", "Cringe",
        "Mood", "Glow up", "Flex", "Tea", "Cap", "Salty", "Slay", "Ghosting",
        "Simp", "Stan", "Clout", "Hype", "Cultura de la cancelación", "Mukbang",
        "Shipping", "Easter egg", "Unboxing", "Haters", "Lurker", "FOMO", "IRL",
        "GOAT", "YOLO", "POV", "ASMR", "Cottagecore", "Dark academia", "Cripto",
        "Web3", "Blockchain", "Deepfake", "Prompt", "Algoritmo", "Shadowban",
        "BeReal", "Threads", "Substack", "OnlyFans", "Patreon", "Kickstarter",
        "BookTok", "BookTuber", "Breadcrumbing", "Orbiting", "Situationship",
        "Delulu", "Rizz",
      ],
      dificil: [
        "Vine", "Tumblr", "Myspace", "Second Life", "Farmville", "Wordle",
        "Coffin Dance", "Wellerman", "Caramelldansen", "Leave Britney Alone",
        "Leeroy Jenkins", "Chocolate Rain", "Charlie Bit My Finger",
        "Keyboard Cat", "Dramatic Chipmunk", "Disaster Girl",
        "Hide the Pain Harold", "Distracted Boyfriend", "Woman Yelling at Cat",
        "Bernie Mittens", "Slender Man", "Creepypasta", "Jeff the Killer",
        "Star Wars Kid", "Numa Numa", "El Risitas", "Edgar de la boda",
        "Pollo Polla", "Berta", "Rayito", "Salchichón", "Chocapic",
        "Mannequin Challenge", "Planking", "Dalgona", "Shitposting",
        "Rage Comic", "Scumbag Steve", "Bad Luck Brian",
        "Overly Attached Girlfriend", "Loss.jpg", "Ugandan Knuckles", "Harambe",
        "Gritty", "Floppa", "Cheems", "Omae wa mou shindeiru", "Crab Rave",
        "To Be Continued", "Evil Kermit", "Expanding Brain", "Galaxy Brain",
        "Visible Confusion", "Stonks", "Drakeposting", "Mocking SpongeBob",
        "This Is Fine", "Pepe Silvia", "Always Has Been", "Is This A Pigeon",
      ],
    },
  },
  {
    id: "historia",
    nombre: "Personajes de la historia",
    emoji: "📜",
    palabras: {
      facil: [
        "Napoleón Bonaparte", "Julio César", "Cleopatra", "Cristóbal Colón",
        "Albert Einstein", "Isaac Newton", "Galileo Galilei", "Leonardo da Vinci",
        "Alejandro Magno", "Mahatma Gandhi", "Martin Luther King",
        "Nelson Mandela", "Winston Churchill", "Abraham Lincoln",
        "George Washington", "Simón Bolívar", "José de San Martín", "Che Guevara",
        "Fidel Castro", "Eva Perón", "Juan Domingo Perón", "Adolf Hitler",
        "Benito Mussolini", "Iósif Stalin", "Mao Zedong", "Pablo Picasso",
        "Vincent van Gogh", "William Shakespeare", "Wolfgang Mozart",
        "Ludwig van Beethoven", "Johann Sebastian Bach", "Marco Polo",
        "Hernán Cortés", "Francisco Pizarro", "Moctezuma", "Tutankamón",
        "Sócrates", "Platón", "Aristóteles", "Juana de Arco", "Manuel Belgrano",
        "Hipólito Yrigoyen", "Domingo Faustino Sarmiento", "Bartolomé Mitre",
        "Benjamín Franklin", "Thomas Jefferson", "John F. Kennedy",
        "Franklin D. Roosevelt", "Theodore Roosevelt", "Margaret Thatcher",
        "Angela Merkel", "Ronald Reagan", "Mijaíl Gorbachov", "Rosa Parks",
        "Malcolm X", "Miguel Ángel", "Juan Pablo II", "Papa Francisco",
        "Diego Velázquez", "Frida Kahlo",
      ],
      medio: [
        "Marie Curie", "Nikola Tesla", "Thomas Edison", "Fiódor Dostoyevski",
        "Lev Tolstói", "Confucio", "Buda", "Jesucristo", "Mahoma", "Moisés",
        "Gengis Kan", "Atila", "Carlomagno", "Isabel I de Inglaterra",
        "María Antonieta", "Luis XIV", "Pedro el Grande", "Catalina la Grande",
        "Iván el Terrible", "Benito Juárez", "Pancho Villa", "Emiliano Zapata",
        "Ho Chi Minh", "Vladímir Lenin", "León Trotsky", "Rosa Luxemburgo",
        "Karl Marx", "Friedrich Engels", "Charlie Chaplin", "Sigmund Freud",
        "Carl Jung", "Charles Darwin", "Johannes Kepler", "Nicolás Copérnico",
        "Pitágoras", "Euclides", "Arquímedes", "Hipócrates", "Homero", "Virgilio",
        "Friedrich Nietzsche", "Arthur Schopenhauer", "Søren Kierkegaard",
        "Friedrich Hegel", "Baruch Spinoza", "René Descartes", "Maquiavelo",
        "Tomás Moro", "Erasmo de Rotterdam", "Francisco de Goya", "Diego Rivera",
        "Salvador Dalí", "Antoni Gaudí", "Gustave Eiffel", "Alejandro Dumas",
        "Víctor Hugo", "Julio Verne", "Miguel de Cervantes", "Lope de Vega",
        "Francisco de Quevedo",
      ],
      dificil: [
        "Akhenatón", "Ramsés II", "Hatshepsut", "Nefertiti", "Ciro el Grande",
        "Jerjes I", "Pericles", "Tucídides", "Heródoto", "Espartaco", "Nerón",
        "Calígula", "Marco Aurelio", "Trajano", "Constantino el Grande",
        "Justiniano I", "Teodora", "Leónidas I", "Asurbanipal", "Nabucodonosor",
        "Saladino", "Ricardo Corazón de León", "Leonor de Aquitania", "Tamerlán",
        "Akbar el Grande", "Solimán el Magnífico", "Atahualpa", "Pachacútec",
        "Túpac Amaru II", "José Martí", "Bernardo O'Higgins", "Miguel Hidalgo",
        "Giuseppe Garibaldi", "Otto von Bismarck", "Maximilien Robespierre",
        "Jean-Jacques Rousseau", "Voltaire", "Montesquieu", "John Locke",
        "Immanuel Kant", "Epicuro", "Zenón de Citio", "Cicerón", "Séneca",
        "Plinio el Viejo", "Enrique VIII", "Carlos V", "Felipe II", "Caupolicán",
        "Lautaro", "Túpac Katari", "Manuela Sáenz", "Agripina", "Boudica",
        "Cayo Mario", "Demócrito", "Heráclito", "Parménides", "Anaximandro",
        "Tales de Mileto",
      ],
    },
  },
  {
    id: "streamers",
    nombre: "Streamers",
    emoji: "🎥",
    palabras: {
      facil: [
        "Ibai Llanos", "AuronPlay", "Rubius", "MrBeast", "Ninja", "Pokimane",
        "PewDiePie", "Markiplier", "Jacksepticeye", "Logan Paul", "Jake Paul",
        "KSI", "xQc", "Dr Disrespect", "Shroud", "Summit1G", "TimTheTatman",
        "TheGrefg", "Vegetta777", "Willyrex", "Mikecrack", "Luzu", "Coscu",
        "Dream", "GeorgeNotFound", "Sapnap", "BadBoyHalo", "TommyInnit",
        "Wilbur Soot", "Philza", "Technoblade", "Valkyrae", "Disguised Toast",
        "Sykkuno", "Corpse Husband", "Lilypichu", "DanTDM", "Stampy", "Ranboo",
        "Tubbo", "Fernanfloo", "JuegaGerman", "ElMariana", "Los Polinesios",
        "El Momo", "Felipe Neto", "Luccas Neto", "Yao Cabrera",
        "Santiago Maratea", "Tomás Mazza", "Davoo Xeneize", "Martín Cirio",
        "Jaime Altozano", "Bizarrap", "Whindersson Nunes", "LDShadowLady",
        "CDMario", "Paulettee", "DeiGamer", "Enry_Kn",
      ],
      medio: [
        "Kai Cenat", "Adin Ross", "IShowSpeed", "ElXokas", "Lolito", "Knekro",
        "Papi Gavi", "Tinieblas Jr", "ElRichMC", "Mayichi", "Ampeterby7", "Staxx",
        "Quackity", "CaptainSparklez", "Mizkif", "Ludwig", "Sodapoppin", "Forsen",
        "Nickmercs", "Symfuhny", "CourageJD", "Nmplol", "Pokelawls", "HasanAbi",
        "Asmongold", "Tfue", "Faze Rug", "SSSniperWolf", "Bretman Rock",
        "Charli D'Amelio", "Addison Rae", "Emma Chamberlain", "David Dobrik",
        "Zach King", "Khaby Lame", "Bella Poarch", "Loren Gray",
        "Dixie D'Amelio", "Tana Mongeau", "Trisha Paytas", "Jschlatt",
        "Rosanna Pansino", "iJustine", "Smosh", "Jacksfilms", "Philip DeFranco",
        "Casey Neistat", "Bethany Mota", "Zoella", "ThatcherJoe", "Alfie Deyes",
        "Ethan Klein", "Shane Dawson", "Cody Ko", "LaurDIY", "Liza Koshy",
        "Tyler Oakley", "AmazingPhil", "NikkieTutorials", "Danisnotonfire",
      ],
      dificil: [
        "Ice Poseidon", "Moistcr1tikal", "Kaceytron", "Greekgodx", "Destiny",
        "Hasan Piker", "Trainwreckstv", "Amouranth", "Alinity", "F1NN5TER",
        "CallMeCarson", "Fitz", "SwaggerSouls", "Nogla", "VanossGaming",
        "MiniLadd", "Ssundee", "Unspeakable", "Preston", "Lazarbeam", "Lachlan",
        "Muselk", "Illojuan", "Alexby11", "Mangel", "Naisenko", "Perxitaa",
        "Zeling", "Biyin", "Cristinini", "Jordi Wild", "DotCSV", "Midudev",
        "HolaSoyGerman", "Juanpa Zurita", "Yuya", "Luisito Comunica",
        "Werevertumorro", "Dross", "Spreen", "Tyler1", "NymN", "Esfand",
        "Rich Campbell", "Emiru", "HAchubby", "JustaMinx", "Maya Higa",
        "QTCinderella", "Macaiyla", "Sypherpk", "ImperialHal", "Aceu",
        "iiTzTimmy", "Boxbox", "Aphromoo", "Voyboy", "Dyrus", "Hikaru Nakamura",
        "Levy Rozman",
      ],
    },
  },
  {
    id: "videojuegos",
    nombre: "Videojuegos",
    emoji: "🎮",
    palabras: {
      facil: [
        "Super Mario Bros", "Luigi", "The Legend of Zelda", "Link", "Minecraft",
        "Fortnite", "Roblox", "Grand Theft Auto", "Call of Duty", "Sonic",
        "Pac-Man", "Tetris", "Among Us", "FIFA", "Pikachu", "Donkey Kong",
        "Mortal Kombat", "Street Fighter", "The Sims", "Angry Birds",
        "Candy Crush", "Crash Bandicoot", "Kirby", "Yoshi", "Bowser", "Mega Man",
        "Lara Croft", "Tomb Raider", "Halo", "Master Chief", "God of War",
        "Kratos", "Assassin's Creed", "Resident Evil", "PlayStation", "Xbox",
        "Nintendo Switch", "Game Boy", "Nintendo 64", "Wii", "Counter-Strike",
        "League of Legends", "Fall Guys", "Pikmin", "Kid Icarus", "Punch-Out",
        "Duck Hunt", "Pokémon Go", "Clash Royale", "Clash of Clans",
        "Subway Surfers", "Temple Run", "Plants vs. Zombies", "Wii Sports",
        "Tamagotchi", "Cut the Rope", "Doodle Jump", "Mario Party",
        "Super Mario 64", "Super Mario Odyssey",
      ],
      medio: [
        "The Witcher", "Geralt de Rivia", "Cyberpunk 2077", "Red Dead Redemption",
        "Skyrim", "Fallout", "Mass Effect", "BioShock", "Portal", "Half-Life",
        "Gordon Freeman", "Uncharted", "Nathan Drake", "The Last of Us",
        "Bayonetta", "Metal Gear Solid", "Solid Snake", "Silent Hill",
        "Devil May Cry", "Dragon Age", "Final Fantasy", "Kingdom Hearts",
        "Monster Hunter", "Dark Souls", "Bloodborne", "Elden Ring", "Diablo",
        "World of Warcraft", "Overwatch", "Valorant", "Apex Legends", "PUBG",
        "Dota 2", "StarCraft", "Age of Empires", "Civilization", "GameCube",
        "Dreamcast", "Sega Genesis", "Mario Kart", "Super Smash Bros",
        "Animal Crossing", "Splatoon", "Rocket League", "Hearthstone",
        "Borderlands", "Fallout: New Vegas", "BioShock Infinite", "Dishonored",
        "Prey", "Control", "Alan Wake", "Max Payne", "Mirror's Edge", "Metro 2033",
        "Sleeping Dogs", "Watch Dogs", "Dying Light", "Dead Space", "Phasmophobia",
      ],
      dificil: [
        "Shenmue", "Chrono Trigger", "Earthbound", "Secret of Mana",
        "Castlevania: Symphony of the Night", "Metroid Prime", "Samus Aran",
        "Ico", "Shadow of the Colossus", "Journey", "Braid", "Limbo", "Inside",
        "Celeste", "Hollow Knight", "Hades", "Cuphead", "Undertale",
        "Stardew Valley", "Terraria", "Disco Elysium", "Planescape: Torment",
        "Baldur's Gate", "Deus Ex", "Okami", "Nier Automata", "Persona 5",
        "Yakuza", "Dragon Quest", "Ninja Gaiden", "Contra", "Tekken",
        "Soul Calibur", "Guilty Gear", "King of Fighters", "Commodore 64",
        "Atari 2600", "Neo Geo", "TurboGrafx-16", "MSX", "ZX Spectrum", "Galaga",
        "Space Invaders", "Phantasy Star", "Panzer Dragoon", "Valkyria Chronicles",
        "Gris", "Hyper Light Drifter", "Hotline Miami", "Enter the Gungeon",
        "Dead Cells", "Spelunky", "Binding of Isaac", "FTL: Faster Than Light",
        "Slay the Spire", "Return of the Obra Dinn", "Outer Wilds",
        "What Remains of Edith Finch", "Valiant Hearts", "Crypt of the NecroDancer",
      ],
    },
  },
  {
    id: "paises",
    nombre: "Países",
    emoji: "🌎",
    palabras: {
      facil: [
        "Argentina", "Brasil", "Chile", "Uruguay", "Paraguay", "Perú", "Bolivia",
        "Colombia", "Venezuela", "Ecuador", "México", "Estados Unidos", "Canadá",
        "España", "Italia", "Francia", "Alemania", "Reino Unido", "Portugal",
        "Rusia", "China", "Japón", "Corea del Sur", "India", "Australia",
        "Egipto", "Sudáfrica", "Marruecos", "Nigeria", "Kenia", "Grecia",
        "Turquía", "Arabia Saudita", "Israel", "Irán", "Irak", "Suecia",
        "Noruega", "Dinamarca", "Finlandia", "Haití", "República Dominicana",
        "Panamá", "Costa Rica", "Nicaragua", "Honduras", "El Salvador",
        "Guatemala", "Puerto Rico", "Jamaica", "Bahamas", "Trinidad y Tobago",
        "Barbados", "Granada", "Santa Lucía", "Belice", "Guyana", "Surinam",
        "Malta", "Luxemburgo",
      ],
      medio: [
        "Islandia", "Irlanda", "Polonia", "Hungría", "Austria", "Suiza",
        "Bélgica", "Países Bajos", "República Checa", "Eslovaquia", "Rumania",
        "Bulgaria", "Croacia", "Serbia", "Ucrania", "Estonia", "Letonia",
        "Lituania", "Corea del Norte", "Vietnam", "Tailandia", "Filipinas",
        "Indonesia", "Malasia", "Singapur", "Pakistán", "Bangladesh", "Sri Lanka",
        "Nepal", "Afganistán", "Siria", "Líbano", "Jordania",
        "Emiratos Árabes Unidos", "Catar", "Kuwait", "Omán", "Yemen",
        "Nueva Zelanda", "Cuba", "Chipre", "Montenegro", "Eslovenia",
        "Macedonia del Norte", "Albania", "Bosnia y Herzegovina", "Kosovo",
        "Moldavia", "Bielorrusia", "Georgia", "Armenia", "Azerbaiyán", "Argelia",
        "Túnez", "Libia", "Sudán", "Senegal", "Ghana", "Camerún", "Madagascar",
      ],
      dificil: [
        "Kirguistán", "Turkmenistán", "Tayikistán", "Uzbekistán", "Kazajistán",
        "Mongolia", "Bután", "Birmania", "Laos", "Camboya", "Timor Oriental",
        "Papúa Nueva Guinea", "Fiyi", "Samoa", "Tonga", "Kiribati", "Vanuatu",
        "Palaos", "Tuvalu", "Nauru", "Eritrea", "Yibuti", "Somalia", "Etiopía",
        "Ruanda", "Burundi", "Uganda", "Tanzania", "Zambia", "Zimbabue",
        "Angola", "Mozambique", "Namibia", "Botsuana", "Lesoto", "Esuatini",
        "Gabón", "Chad", "Níger", "Malí", "Mauritania", "Burkina Faso",
        "Guinea", "Guinea-Bisáu", "Guinea Ecuatorial", "Sierra Leona", "Liberia",
        "Togo", "Benín", "República Centroafricana", "República del Congo",
        "República Democrática del Congo", "Santo Tomé y Príncipe", "Cabo Verde",
        "Comoras", "Seychelles", "Mauricio", "Maldivas", "Baréin", "San Marino",
      ],
    },
  },
  {
    id: "mezcla",
    nombre: "Mezcla total",
    emoji: "🎲",
    palabras: {
      facil: [
        "Playa", "Aeropuerto", "Hospital", "Estadio",
        "Cepillo de dientes", "Espejo", "Reloj", "Cama",
        "Médico", "Bombero", "Policía", "Cocinero",
        "Titanic", "Frozen", "Harry Potter", "Star Wars",
        "León", "Tigre", "Elefante", "Perro",
        "Shakira", "Bad Bunny", "Taylor Swift", "Elon Musk",
        "Pizza", "Hamburguesa", "Empanada", "Sushi",
        "Messi", "Michael Jordan", "La Mano de Dios", "Cristiano Ronaldo",
        "Spider-Man", "Batman", "Superman", "Iron Man",
        "TikTok", "YouTube", "K-pop", "Netflix",
        "Napoleón Bonaparte", "Albert Einstein", "Cleopatra", "Cristóbal Colón",
        "Ibai Llanos", "MrBeast", "Rubius", "AuronPlay",
        "Super Mario Bros", "Minecraft", "Fortnite", "Pac-Man",
        "Argentina", "Brasil", "España", "México",
        "Mujer Maravilla", "Avatar", "Elvis Presley", "Estados Unidos",
      ],
      medio: [
        "Observatorio", "Faro", "Mansión", "Coliseo",
        "Tijera", "Martillo", "Taladro", "Aspiradora",
        "Cirujano", "Abogado", "Ingeniero", "Programador",
        "El Padrino", "Pulp Fiction", "Interestelar", "Whiplash",
        "Camello", "Leopardo", "Canguro", "Cóndor",
        "Harry Styles", "Zendaya", "Timothée Chalamet", "Pedro Pascal",
        "Paella", "Ceviche", "Ramen", "Tiramisú",
        "Jude Bellingham", "Luka Dončić", "La Atajada del Dibu", "Robert Lewandowski",
        "Soldado de Invierno", "Doctor Doom", "Rorschach", "Silver Surfer",
        "Bitcoin", "NFT", "ChatGPT", "Cripto",
        "Marie Curie", "Nikola Tesla", "Gengis Kan", "Maquiavelo",
        "Kai Cenat", "IShowSpeed", "ElXokas", "Ludwig",
        "The Witcher", "Elden Ring", "Mario Kart", "BioShock",
        "Islandia", "Pakistán", "Chipre", "Argelia",
        "The Last of Us", "Croissant", "Charlie Chaplin", "Cottagecore",
      ],
      dificil: [
        "Reactor nuclear", "Búnker", "Géiser", "Caldera volcánica",
        "Astrolabio", "Sextante", "Microscopio", "Compás",
        "Forense", "Arqueólogo", "Perfumista", "Lexicógrafo",
        "Persona", "Mulholland Drive", "Relatos Salvajes", "Oldboy",
        "Narval", "Axolote", "Capibara", "Yacaré",
        "Kendrick Lamar", "Tyler the Creator", "Saoirse Ronan", "Anya Taylor-Joy",
        "Bullabesa", "Pho", "Bibimbap", "Kimchi",
        "Juan Román Riquelme", "Manu Ginóbili", "La Cucharita de Panenka", "Gianluigi Buffon",
        "Caballero Luna", "Omni-Man", "Apocalipsis", "Mister Siniestro",
        "Coffin Dance", "El Risitas", "Edgar de la boda", "Stonks",
        "Akhenatón", "Saladino", "Maximilien Robespierre", "Séneca",
        "Ice Poseidon", "Moistcr1tikal", "Destiny", "Tyler1",
        "Shadow of the Colossus", "Disco Elysium", "Outer Wilds", "Hades",
        "Kirguistán", "Bután", "Mauritania", "Burkina Faso",
        "Dolmen", "Escalímetro", "Polaris", "Rivaldo",
      ],
    },
  },
];

export function buscarCategoria(id: string) {
  return CATEGORIAS.find((c) => c.id === id);
}
