import type { Categoria } from "./types";

export const CATEGORIAS: Categoria[] = [
  {
    id: "lugares",
    nombre: "Lugares",
    emoji: "📍",
    palabras: {
      facil: [
        "Playa", "Aeropuerto", "Hospital", "Estadio", "Biblioteca", "Escuela",
        "Iglesia", "Banco", "Cine", "Restaurante", "Parque", "Supermercado",
        "Farmacia", "Cárcel", "Gimnasio", "Hotel", "Casino", "Zoológico",
        "Circo", "Bar", "Cafetería", "Panadería", "Peluquería", "Mercado",
        "Plaza", "Cementerio", "Museo", "Teatro", "Estación de tren", "Puerto",
        "Castillo", "Granja", "Bosque", "Montaña", "Desierto", "Selva",
        "Río", "Lago", "Isla", "Volcán",
      ],
      medio: [
        "Observatorio", "Faro", "Acueducto", "Catacumbas", "Mansión", "Refugio",
        "Embajada", "Tribunal", "Laboratorio", "Astillero", "Mina", "Cantera",
        "Fábrica", "Almacén", "Estudio de televisión", "Estudio de grabación",
        "Pista de patinaje", "Boliche", "Karaoke", "Bowling", "Spa", "Sauna",
        "Crucero", "Submarino", "Estación espacial", "Cabaña", "Iglú", "Pirámide",
        "Coliseo", "Palacio", "Monasterio", "Abadía", "Sinagoga", "Mezquita",
        "Templo", "Pagoda", "Hipódromo", "Velódromo", "Ring de boxeo", "Vivero",
      ],
      dificil: [
        "Reactor nuclear", "Búnker", "Refinería", "Catedral gótica", "Mausoleo",
        "Anfiteatro romano", "Acuario público", "Planetario", "Hangar",
        "Estación de bomberos", "Comisaría", "Morgue", "Sala de operaciones",
        "Sala de calderas", "Bodega de vino", "Destilería", "Cervecería artesanal",
        "Aserradero", "Curtiembre", "Salina", "Géiser", "Cráter", "Cenote",
        "Manglar", "Sabana", "Tundra", "Páramo", "Estepa", "Iceberg", "Atolón",
        "Fiordo", "Cañón", "Meseta", "Acantilado", "Arrecife de coral",
        "Cueva submarina", "Glaciar", "Oasis", "Pozo petrolero", "Salar",
      ],
    },
  },
  {
    id: "profesiones",
    nombre: "Profesiones",
    emoji: "💼",
    palabras: {
      facil: [
        "Médico", "Profesor", "Bombero", "Policía", "Cocinero", "Panadero",
        "Carpintero", "Plomero", "Electricista", "Mecánico", "Cartero", "Taxista",
        "Camionero", "Piloto", "Azafata", "Veterinario", "Dentista", "Enfermero",
        "Peluquero", "Albañil", "Pintor", "Jardinero", "Granjero", "Pescador",
        "Cantante", "Actor", "Bailarín", "Músico", "Futbolista", "Boxeador",
        "Tenista", "Nadador", "Periodista", "Fotógrafo", "Escritor", "Dibujante",
        "Mago", "Payaso", "Astronauta", "Soldado",
      ],
      medio: [
        "Cirujano", "Abogado", "Juez", "Arquitecto", "Ingeniero", "Programador",
        "Diseñador gráfico", "Contador", "Economista", "Psicólogo", "Psiquiatra",
        "Pediatra", "Cardiólogo", "Oculista", "Optometrista", "Quiropráctico",
        "Sastre", "Modista", "Joyero", "Relojero", "Zapatero", "Florista",
        "Sommelier", "Repostero", "Heladero", "Carnicero", "Pescadero", "Apicultor",
        "Buzo", "Salvavidas", "Guardabosque", "Domador", "Adiestrador", "Locutor",
        "Comentarista deportivo", "Director de cine", "Productor", "Guionista",
        "Coreógrafo", "Estilista",
      ],
      dificil: [
        "Forense", "Antropólogo", "Arqueólogo", "Paleontólogo", "Astrofísico",
        "Biólogo marino", "Geólogo", "Vulcanólogo", "Sismólogo", "Meteorólogo",
        "Climatólogo", "Etólogo", "Ornitólogo", "Entomólogo", "Botánico",
        "Taxidermista", "Calígrafo", "Lutier", "Restaurador de obras",
        "Curador de arte", "Anticuario", "Tasador", "Notario", "Escribano",
        "Diplomático", "Embajador", "Cónsul", "Traductor jurídico", "Catador",
        "Maestro chocolatero", "Maestro quesero", "Tonelero", "Herrero",
        "Forjador", "Vidriero", "Ebanista", "Talabartero", "Sereno", "Acuñador",
        "Perfumista",
      ],
    },
  },
  {
    id: "animales",
    nombre: "Animales",
    emoji: "🦁",
    palabras: {
      facil: [
        "León", "Tigre", "Elefante", "Jirafa", "Cebra", "Hipopótamo", "Rinoceronte",
        "Mono", "Oso", "Lobo", "Zorro", "Conejo", "Ardilla", "Caballo", "Vaca",
        "Cerdo", "Oveja", "Cabra", "Gallina", "Perro", "Gato", "Ratón", "Ballena",
        "Tiburón", "Delfín", "Pulpo", "Cangrejo", "Pez", "Tortuga", "Cocodrilo",
        "Serpiente", "Águila", "Loro", "Pingüino", "Pato", "Búho", "Mariposa",
        "Abeja", "Hormiga", "Araña",
      ],
      medio: [
        "Camello", "Llama", "Alpaca", "Búfalo", "Antílope", "Gacela", "Ñu",
        "Hiena", "Leopardo", "Pantera", "Puma", "Lince", "Mapache", "Castor",
        "Nutria", "Foca", "Morsa", "Manatí", "Orca", "Manta raya",
        "Caballito de mar", "Estrella de mar", "Erizo de mar", "Medusa",
        "Calamar", "Langosta", "Camarón", "Cóndor", "Halcón", "Flamenco",
        "Pelícano", "Tucán", "Avestruz", "Emú", "Kiwi", "Ornitorrinco", "Koala",
        "Canguro", "Wombat", "Perezoso",
      ],
      dificil: [
        "Narval", "Beluga", "Cachalote", "Marsopa", "Vaquita marina", "Axolote",
        "Salamandra", "Tritón", "Iguana", "Camaleón", "Dragón de Komodo", "Gavial",
        "Tapir", "Okapi", "Quokka", "Numbat", "Pangolín", "Armadillo",
        "Oso hormiguero", "Suricata", "Glotón", "Zarigüeya", "Murciélago",
        "Tarsero", "Aye-aye", "Lemur", "Surubí", "Pirarucú", "Anguila eléctrica",
        "Quetzal", "Casuario", "Albatros", "Frailecillo", "Cormorán",
        "Garza real", "Martín pescador", "Colibrí", "Polilla luna", "Escorpión",
        "Capibara",
      ],
    },
  },
  {
    id: "comidas",
    nombre: "Comidas y bebidas",
    emoji: "🍕",
    palabras: {
      facil: [
        "Pizza", "Hamburguesa", "Pancho", "Empanada", "Sándwich", "Milanesa",
        "Pollo asado", "Bife", "Pasta", "Espagueti", "Lasaña", "Sopa", "Ensalada",
        "Arroz", "Tortilla", "Tacos", "Burrito", "Sushi", "Helado", "Torta",
        "Galleta", "Chocolate", "Caramelo", "Manzana", "Banana", "Naranja",
        "Frutilla", "Sandía", "Pan", "Queso", "Café", "Té", "Leche",
        "Jugo de naranja", "Agua mineral", "Cerveza", "Vino", "Limonada",
        "Chocolate caliente", "Gaseosa",
      ],
      medio: [
        "Paella", "Risotto", "Ramen", "Pad thai", "Curry", "Falafel", "Hummus",
        "Kebab", "Ceviche", "Asado", "Choripán", "Guacamole", "Tamales", "Mole",
        "Arepa", "Pupusa", "Locro", "Humita", "Provoleta", "Croqueta",
        "Tarta de manzana", "Tiramisú", "Cheesecake", "Crème brûlée", "Fondue",
        "Raclette", "Croissant", "Bagel", "Pretzel", "Dulce de leche", "Alfajor",
        "Mate", "Café con leche", "Cappuccino", "Espresso", "Daiquiri", "Mojito",
        "Margarita", "Sangría", "Champagne",
      ],
      dificil: [
        "Bouillabaisse", "Coq au vin", "Beef wellington", "Carbonara", "Osobuco",
        "Carpaccio", "Bruschetta", "Caprese", "Gazpacho", "Pulpo a la gallega",
        "Bacalao a la vizcaína", "Cochinillo", "Pato pekinés", "Dim sum", "Wonton",
        "Tom yum", "Pho", "Bibimbap", "Kimchi", "Tempura", "Sashimi", "Onigiri",
        "Mochi", "Baklava", "Tahini", "Tabule", "Couscous", "Moussaka", "Pierogi",
        "Goulash", "Strudel", "Macaron", "Profiterol", "Praliné",
        "Trufa de chocolate", "Absenta", "Hidromiel", "Sake", "Pisco sour",
        "Caipirinha",
      ],
    },
  },
  {
    id: "cine",
    nombre: "Películas y series",
    emoji: "🎬",
    palabras: {
      facil: [
        "Titanic", "Avatar", "Frozen", "Shrek", "Coco", "Toy Story", "Cars",
        "Buscando a Nemo", "El Rey León", "Aladdín", "Harry Potter",
        "El Señor de los Anillos", "Star Wars", "Indiana Jones", "Rocky",
        "Rápido y Furioso", "Misión Imposible", "Jurassic Park", "Tiburón",
        "E.T.", "Terminator", "Forrest Gump", "Matrix", "Karate Kid",
        "Volver al Futuro", "Hombres de Negro", "La Casa de Papel",
        "Stranger Things", "Breaking Bad", "Game of Thrones", "The Office",
        "Friends", "Los Simpson", "Bob Esponja", "Pokémon", "Dragon Ball",
        "Peppa Pig", "Scooby-Doo", "Tom y Jerry", "El Chavo del 8",
      ],
      medio: [
        "El Padrino", "Pulp Fiction", "El Club de la Pelea", "Gladiador",
        "Braveheart", "El Origen", "Interestelar", "El Caballero de la Noche",
        "Joker", "Parásitos", "El Sexto Sentido", "El Resplandor", "Psicosis",
        "Vértigo", "Casablanca", "Lo que el viento se llevó", "Citizen Kane",
        "La Naranja Mecánica", "La Lista de Schindler",
        "Salvando al Soldado Ryan", "Apocalypse Now", "Cadena Perpetua",
        "Doce Hombres en Pugna", "El Silencio de los Inocentes", "Halloween",
        "Pesadilla en Elm Street", "Viernes 13", "El Exorcista", "Alien",
        "Depredador", "Robocop", "Mad Max", "El Viaje de Chihiro",
        "La Princesa Mononoke", "La Vida es Bella", "Cinema Paradiso", "Amélie",
        "Whiplash", "La La Land", "Dune",
      ],
      dificil: [
        "Persona", "Stalker", "El Espejo", "Andrei Rublev", "Sátántangó",
        "Mulholland Drive", "Eraserhead", "La Dolce Vita", "8½",
        "El Año Pasado en Marienbad", "Hiroshima Mon Amour", "Cleo de 5 a 7",
        "Sin Aliento", "Los 400 Golpes", "La Ventana Indiscreta", "Roma",
        "Cría Cuervos", "El Espíritu de la Colmena", "Stroszek",
        "Aguirre la Cólera de Dios", "La Montaña Sagrada", "Suspiria",
        "Possession", "La Pianista", "Funny Games", "El Verdugo",
        "Plácido", "Bienvenido Mr. Marshall", "La Estrategia del Caracol",
        "El Abrazo de la Serpiente", "La Historia Oficial",
        "Tiempo de Revancha", "Esperando la Carroza", "Pizza Birra Faso",
        "El Bonaerense", "El Secreto de sus Ojos", "Relatos Salvajes",
        "Anatomía de una Caída", "Tár", "La Sociedad de la Nieve",
      ],
    },
  },
  {
    id: "deportes",
    nombre: "Deportes",
    emoji: "⚽",
    palabras: {
      facil: [
        "Fútbol", "Básquet", "Vóley", "Tenis", "Natación", "Atletismo", "Boxeo",
        "Karate", "Judo", "Ciclismo", "Automovilismo", "Motociclismo", "Surf",
        "Esquí", "Snowboard", "Patinaje", "Skate", "Golf", "Béisbol", "Hockey",
        "Rugby", "Críquet", "Bádminton", "Tenis de mesa", "Pádel", "Ajedrez",
        "Damas", "Bowling", "Billar", "Pesca", "Caza", "Equitación", "Polo",
        "Esgrima", "Tiro al arco", "Halterofilia", "Gimnasia", "Yoga", "Pilates",
        "Maratón",
      ],
      medio: [
        "Triatlón", "Pentatlón moderno", "Decatlón", "Heptatlón", "Salto en alto",
        "Salto con garrocha", "Salto largo", "Salto triple", "Lanzamiento de bala",
        "Lanzamiento de jabalina", "Lanzamiento de disco", "Lanzamiento de martillo",
        "Curling", "Patinaje artístico", "Patinaje de velocidad", "Bobsleigh",
        "Luge", "Skeleton", "Biatlón", "Saltos de esquí", "Esquí acuático",
        "Wakeboard", "Kitesurf", "Windsurf", "Vela", "Remo", "Canotaje", "Kayak",
        "Waterpolo", "Rugby seven", "Fútbol americano", "Lacrosse", "Sóftbol",
        "Squash", "Frontón", "Pelota vasca", "Petanca", "Buceo", "Apnea",
        "Escalada deportiva",
      ],
      dificil: [
        "Sambo", "Jiu-jitsu brasileño", "Krav Maga", "Kendo", "Aikido",
        "Taekwondo", "Capoeira", "Muay Thai", "Sumo", "Lucha grecorromana",
        "Lucha libre olímpica", "Bandy", "Hurling", "Camogie", "Sepak Takraw",
        "Korfball", "Netball", "Fútbol gaélico", "Calcio storico", "Hornussen",
        "Jai alai", "Snooker", "Carambola", "Cornhole", "Pickleball",
        "Speedminton", "Footgolf", "Headis", "Chess boxing", "Octopush",
        "Quidditch", "Slacklining", "Highline", "Bouldering", "Parkour",
        "Geocaching", "Crossfit", "Spikeball", "Disc golf", "Roller derby",
      ],
    },
  },
  {
    id: "objetos",
    nombre: "Objetos cotidianos",
    emoji: "🪥",
    palabras: {
      facil: [
        "Cepillo de dientes", "Pasta de dientes", "Peine", "Cepillo", "Toalla",
        "Jabón", "Champú", "Espejo", "Reloj", "Despertador", "Cama", "Almohada",
        "Sábana", "Manta", "Mesa", "Silla", "Sofá", "Sillón", "Lámpara", "Vela",
        "Linterna", "Paraguas", "Sombrero", "Anteojos", "Mochila", "Cartera",
        "Billetera", "Llaves", "Celular", "Computadora", "Televisión",
        "Control remoto", "Auriculares", "Cámara de fotos", "Cuchillo",
        "Tenedor", "Cuchara", "Plato", "Vaso", "Taza",
      ],
      medio: [
        "Tijera", "Pinza", "Martillo", "Destornillador", "Llave inglesa",
        "Cinta métrica", "Nivel", "Taladro", "Sierra", "Pala", "Rastrillo",
        "Manguera", "Regadera", "Maceta", "Escoba", "Aspiradora", "Plancha",
        "Tabla de planchar", "Lavarropas", "Secarropas", "Heladera", "Microondas",
        "Horno", "Tostadora", "Licuadora", "Batidora", "Cafetera",
        "Pava eléctrica", "Termo", "Bandeja", "Sartén", "Olla", "Colador",
        "Rallador", "Abrelatas", "Sacacorchos", "Cucharón", "Espátula", "Mortero",
        "Embudo",
      ],
      dificil: [
        "Astrolabio", "Sextante", "Brújula", "Catalejo", "Microscopio",
        "Estetoscopio", "Termómetro", "Barómetro", "Higrómetro", "Anemómetro",
        "Pluviómetro", "Tensiómetro", "Lupa", "Caleidoscopio", "Diapasón",
        "Metrónomo", "Teodolito", "Plomada", "Compás", "Transportador",
        "Escuadra", "Cartabón", "Pantógrafo", "Yunque", "Fuelle", "Soplete",
        "Cincel", "Buril", "Gubia", "Lima", "Esmeril", "Garlopa",
        "Cepillo de carpintero", "Berbiquí", "Punzón", "Calibre", "Goniómetro",
        "Estilete", "Aerógrafo", "Tipómetro",
      ],
    },
  },
  {
    id: "famosos",
    nombre: "Famosos internacionales",
    emoji: "⭐",
    palabras: {
      facil: [
        "Messi", "Cristiano Ronaldo", "Neymar", "Maradona", "Pelé",
        "Michael Jordan", "LeBron James", "Roger Federer", "Rafael Nadal",
        "Serena Williams", "Tiger Woods", "Usain Bolt", "Mike Tyson",
        "Muhammad Ali", "Beyoncé", "Rihanna", "Madonna", "Lady Gaga", "Shakira",
        "Bad Bunny", "Taylor Swift", "Justin Bieber", "Michael Jackson",
        "Elvis Presley", "Freddie Mercury", "John Lennon", "Paul McCartney",
        "Bob Marley", "Eminem", "Drake", "Tom Cruise", "Brad Pitt",
        "Leonardo DiCaprio", "Will Smith", "Robert Downey Jr.",
        "Scarlett Johansson", "Angelina Jolie", "Jennifer Aniston",
        "Penélope Cruz", "Antonio Banderas",
      ],
      medio: [
        "Albert Einstein", "Isaac Newton", "Stephen Hawking", "Charles Darwin",
        "Marie Curie", "Nikola Tesla", "Thomas Edison", "Galileo Galilei",
        "Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí",
        "Frida Kahlo", "Diego Rivera", "Walt Disney", "Steve Jobs", "Bill Gates",
        "Mark Zuckerberg", "Elon Musk", "Jeff Bezos", "Barack Obama",
        "Donald Trump", "Vladimir Putin", "Angela Merkel", "Nelson Mandela",
        "Mahatma Gandhi", "Martin Luther King", "Winston Churchill",
        "Napoleón Bonaparte", "Julio César", "Cleopatra", "Cristóbal Colón",
        "Marco Polo", "Hernán Cortés", "Simón Bolívar", "José de San Martín",
        "Che Guevara", "Fidel Castro", "Eva Perón", "Juan Domingo Perón",
      ],
      dificil: [
        "Marcel Duchamp", "Andy Warhol", "Jackson Pollock", "Mark Rothko",
        "Banksy", "Yayoi Kusama", "Marina Abramović", "Ai Weiwei", "Anish Kapoor",
        "Damien Hirst", "Jean-Michel Basquiat", "Keith Haring", "Cindy Sherman",
        "Frank Gehry", "Zaha Hadid", "Norman Foster", "Renzo Piano", "Tadao Ando",
        "Oscar Niemeyer", "Antoni Gaudí", "Le Corbusier", "Frank Lloyd Wright",
        "Mies van der Rohe", "Walter Gropius", "Massimo Vignelli", "Paula Scher",
        "Stefan Sagmeister", "Dieter Rams", "Philippe Starck", "Karl Lagerfeld",
        "Coco Chanel", "Christian Dior", "Yves Saint Laurent",
        "Alexander McQueen", "Vivienne Westwood", "Issey Miyake", "Rei Kawakubo",
        "Anna Wintour", "David Carson", "Milton Glaser",
      ],
    },
  },
];

export function buscarCategoria(id: string) {
  return CATEGORIAS.find((c) => c.id === id);
}
